trigger:
  branches:
    include:
      - main
pool:
  name: Azure Pipelines
stages:
  jobs:
  - job:Restore
    steps:
    - task: DotNetCoreCLI@2
      displayName: Restore
      inputs:
        command: restore
        projects: '**/*.csproj'
        feedsToUse: config
        nugetConfigPath: NuGet.config    # Relative to root of the repository
  - job:Build
      steps:
      - task: DotNetCoreCLI@2
        displayName: Build
        inputs:
          command: build
          projects: '**/*.csproj'
          arguments: '--configuration $(buildConfiguration)' # Update this to match your need  